_mover = _this select 0;
_id = _this select 2;
_module = _this select 3 select 0;
_attachpoints = _this select 3 select 1;
_atz = _attachpoints select 2;

_module attachto [_mover, [0,-3.7,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-4.1,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-4.5,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-4.9,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-5.3,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-5.7,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-6.1,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-6.5,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-6.9,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-7.3,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-7.7,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-8.1,_atz]];
sleep 0.05;
_module attachto [_mover, [0,-8.9,_atz]];
sleep 0.05;
detach _module;
_module setVelocity [0, 0, -0.1];
_module enableRopeAttach true;
_mover removeAction _id;
_mover addaction ["Container aufladen", "scripts\hemtt\load.sqf", [0,-2.7,_atz]]